/**
 * LIMPIAR LA BASE DE DATOS
 */
drop table CARRITO_COMPRA_PRODUCTO if exists;
drop table ORDEN_PRODUCTO if exists;
drop table PRODUCTO if exists;
drop table CARRITO_COMPRA if exists;
drop table ORDEN if exists;  
drop table USUARIO if exists;
drop table TIPO_USUARIO if exists;
drop table CATEGORIA if exists;

create table CARRITO_COMPRA (
    CODIGO bigint generated by default as identity,
    ESTADO varchar(255),
    FECHA_ACTUALIZACION timestamp,
    FECHA_CREACION timestamp,
    CODIGO_USUARIO bigint,
    primary key (CODIGO)
);

create table CARRITO_COMPRA_PRODUCTO (
    CODIGO bigint generated by default as identity,
    ESTADO varchar(255),
    FECHA_ACTUALIZACION timestamp,
    FECHA_CREACION timestamp,
    CANTIDAD integer,
    DESCUENTO double,
    PRECIO double,
    SKU varchar(255),
    CODIGO_CARRITO_COMPRA bigint,
    CODIGO_PRODUCTO bigint,
    primary key (CODIGO)
);

create table CATEGORIA (
    CODIGO bigint generated by default as identity,
    ESTADO varchar(255),
    FECHA_ACTUALIZACION timestamp,
    FECHA_CREACION timestamp,
    CODIGO_CATEGORIA_PADRE bigint,
    DESCRIPCION varchar(255),
    NOMBRE varchar(255),
    SLUG varchar(255),
    URL_IMAGEN varchar(255),
    primary key (CODIGO)
);

create table ORDEN (
    CODIGO bigint generated by default as identity,
    ESTADO varchar(255),
    FECHA_ACTUALIZACION timestamp,
    FECHA_CREACION timestamp,
    DESCUENTO double,
    GRAN_TOTAL double,
    IMPUESTO double,
    SUB_TOTAL double,
    TOTAL double,
    CODIGO_USUARIO bigint,
    primary key (CODIGO)
);

create table ORDEN_PRODUCTO (
    CODIGO bigint generated by default as identity,
    ESTADO varchar(255),
    FECHA_ACTUALIZACION timestamp,
    FECHA_CREACION timestamp,
    CANTIDAD integer,
    DESCUENTO double,
    PRECIO double,
    SKU varchar(255),
    CODIGO_ORDEN bigint,
    CODIGO_PRODUCTO bigint,
    primary key (CODIGO)
);

create table PRODUCTO (
    CODIGO bigint generated by default as identity,
    ESTADO varchar(255),
    FECHA_ACTUALIZACION timestamp,
    FECHA_CREACION timestamp,
    CANTIDAD integer,
    DESCUENTO double,
    PRECIO double,
    SKU varchar(255),
    COSTO_COMPRA double,
    COSTO_VENTA double,
    DESCRIPCION varchar(255),
    FECHA_PUBLICACION timestamp,
    RESUMEN varchar(255),
    SLUG varchar(255),
    TITULO varchar(255),
    URL_IMAGEN varchar(3000),
    CODIGO_CATEGORIA bigint,
    CODIGO_USUARIO bigint,
    primary key (CODIGO)
);

create table TIPO_USUARIO (
    CODIGO bigint generated by default as identity,
    ESTADO varchar(255),
    FECHA_ACTUALIZACION timestamp,
    FECHA_CREACION timestamp,
    DESCRIPCION varchar(255),
    TIPO varchar(255),
    primary key (CODIGO)
);

create table USUARIO (
    CODIGO bigint generated by default as identity,
    ESTADO varchar(255),
    FECHA_ACTUALIZACION timestamp,
    FECHA_CREACION timestamp,
    APELLIDO varchar(255),
    CELULAR varchar(255),
    CORREO_ELECTRONICO varchar(255),
    HASH_CLAVE varchar(255),
    NOMBRE varchar(255),
    CODIGO_TIPO_USUARIO bigint,
    primary key (CODIGO)
);

alter table CARRITO_COMPRA 
    add constraint FKhm8nk0x2v8ol1o5t64etj6kn3 
    foreign key (CODIGO_USUARIO) 
    references USUARIO;

alter table CARRITO_COMPRA_PRODUCTO 
    add constraint FKcyk6s9g3ysh6ybxrk6ysbdj3t 
    foreign key (CODIGO_CARRITO_COMPRA) 
    references CARRITO_COMPRA;

alter table CARRITO_COMPRA_PRODUCTO 
    add constraint FKhdhn4ac4aj0k68px1p9kqdiiy 
    foreign key (CODIGO_PRODUCTO) 
    references PRODUCTO;

alter table CATEGORIA 
    add constraint FKminlsud0ir8rkvev325i3k7uk 
    foreign key (CODIGO_CATEGORIA_PADRE) 
    references CATEGORIA;

alter table ORDEN 
    add constraint FKk716jq3ti1bkuf598e1hfstiv 
    foreign key (CODIGO_USUARIO) 
    references USUARIO;

alter table ORDEN_PRODUCTO 
    add constraint FK3d3nkdofr3lnpv8sor7xfkcif 
    foreign key (CODIGO_ORDEN) 
    references ORDEN;

alter table ORDEN_PRODUCTO 
    add constraint FK2fhxoegsfs54kdrnkfi4mfo3i 
    foreign key (CODIGO_PRODUCTO) 
    references PRODUCTO;

alter table PRODUCTO 
    add constraint FKk8eugmj5du297309beubandkw 
    foreign key (CODIGO_CATEGORIA) 
    references CATEGORIA;

alter table PRODUCTO 
    add constraint FKh03drdngpwx05gr8slgredau7 
    foreign key (CODIGO_USUARIO) 
    references USUARIO;

alter table USUARIO 
    add constraint FK1beth9ukrjqv6d6hrg1b1vudl 
    foreign key (CODIGO_TIPO_USUARIO) 
    references TIPO_USUARIO;